export const survivorTypes = [
  {
    id: 0,
    name: "CAREGIVER",
    type:"Caregiver",
    image: "/hershel1.png",
    attributes: {
      Strength: 2,
      Agility: 3,
      Trustworthiness: 8,
      Intelligence: 8,
      Courage: 5,
      Endurance: 6,
      Leadership: 5,
    },
    skills: ["Field Medicine", "Psychological Support", "Cooking"],
  },
  {
    id: 1,
    name: "HERO",
    type: "Hero",
    image: "/rick.png",
    attributes: {
      Strength: 9,
      Agility: 5,
      Trustworthiness: 2,
      Intelligence: 3,
      Courage: 8,
      Endurance: 6,
      Leadership: 6,
    },
    skills: ["Marksman", "Heavy Weapons", "Blunt Weapons"],
  },
  {
    id: 2,
    name: "OUTLAW",
    type: "Outlaw",
    image: "/daryl.png",
    attributes: {
      Strength: 7,
      Agility: 9,
      Trustworthiness: 1,
      Intelligence: 5,
      Courage: 6,
      Endurance: 6,
      Leadership: 3,
    },
    skills: [
      "Improvised Combat",
      "Stealth Combat",
      "Intimidation",
      "Trap Setting",
    ],
  },
  {
    id: 3,
    name: "LEADER",
    type: "Leader",
    image: "/deanWarrior.png",
    // Same defaults as the backend's SurvivorType.LEADER
    attributes: {
      Strength: 10,
      Agility: 10,
      Trustworthiness: 10,
      Intelligence: 10,
      Courage: 10,
      Endurance: 10,
      Leadership: 10,
    },
    skills: ["Leadership", "Motivational Speaking", "Negotiation"],
  },
];
